server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location = /health {
    add_header Content-Type text/plain;
    try_files /health =200;
  }

  location /Product/ {
    return 301 /products;
  }

  location /applications/ {
    return 301 /applications;
  }

  location /mosfet_support {
    return 301 /technology;
  }

  location /contact {
    return 301 /about;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
